In [1]:
import numpy as np
import matplotlib.pylab as plt
from math import exp,log,sqrt,pi,sin
import scipy.stats as sts
import pandas as pd
%matplotlib inline

In [62]:
n = 10
tabla = pd.DataFrame(columns=['X','Y'],index=range(1,n+1))
tabla['X'] = np.random.uniform(0,1,n)
tabla['Y'] = tabla['X']+np.random.normal(0,0.1,n)
tabla['$|Z|$'] = abs(tabla['X'] - tabla['Y'])
tabla = tabla.sort_values(['$|Z|$'])
tabla['R'] = range(1,n+1)
tabla = tabla.sort_index()
tabla['$\\varphi$'] = 1*((tabla['X'] - tabla['Y'])>0)
tabla['$R\\varphi$'] = tabla['R']*tabla['$\\varphi$']
T = sum(tabla['$R\\varphi$'])
print(T)
tabla

33

           X         Y     $|Z|$   R  $\varphi$  $R\varphi$
1   0.258435  0.425721  0.167286   9          0           0
2   0.061426  0.233799  0.172374  10          0           0
3   0.842179  0.899737  0.057558   3          0           0
4   0.473682  0.451198  0.022485   1          1           1
5   0.891583  0.745814  0.145768   8          1           8
6   0.247643  0.175895  0.071748   4          1           4
7   0.936111  0.813568  0.122543   6          1           6
8   0.008231 -0.064966  0.073197   5          1           5
9   0.888145  0.753687  0.134458   7          1           7
10  0.512724  0.459493  0.053231   2          1           2